services:
  mongodb:
    image: mongo:7-jammy
    container_name: oldvibes-db-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: oldvibes
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:7-alpine
    container_name: oldvibes-db-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass password --appendonly yes
    volumes:
      - ./data/redis:/data

  mongo-express:
    image: mongo-express:latest
    container_name: oldvibes-db-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
